<html>
<head>
<title>Proefdruk</title>
</head>
<body style="background:#fff;font-family:arial;">
<table border="0" align="center" cellpadding="0" cellspacing="0" style="white-space: inherit;border:1px solid #ccc; padding:10px;width:696px;">
  <tr>
    <td colspan="2" style="padding:10px;">
<img alt="Multisafepay" src="http://proefdruk.factorygroep.nl/app/proefdruk/img/mail-logo2.jpg" />
</td>
  </tr>
  <tr>
    <td colspan="2"><div style="font:20px Arial, Helvetica, sans-serif; color:#000; padding:20px 0 20px 0px; float:left; width:100%">Beste <?php echo $this->name;?>,</div></td>
  </tr>
  <tr>
    <td colspan="2"><div style="font:bold 15px Arial, Helvetica, sans-serif; color:#000; padding:20px 0 20px 0px; float:left; width:100%;"> Bedankt voor het beoordelen van onze digitale proedruk: <?php echo $this->proof_number; ?> </td>
  </tr>

  <tr>
    <td colspan="2"><p style="font:13px Arial, Helvetica, sans-serif;">
U heeft ervoor gekozen de proefdruk te weigeren. We zullen uw opmerkingen verwerken in een nieuwe proefdruk.<br>
  De nieuwe digitale proefdruk zullen we u zo spoedig als mogelijk  per mail versturen.<br>
  <br>

		</p></td>
  </tr>

<tr>
    <td colspan="2">
    	<p style="margin-top:50px; font:13px Arial, Helvetica, sans-serif;">
		Mocht u nog vragen hebben dan vernemen wij dit natuurlijk graag.	
		
		<br /><br/>
-Bel ons op NL: 085- 7325 999 of BE: 03 / 500 9417
<br />
-Mail ons: <a href="info@factorygroep.nl">info@factorygroep.nl</a> 
</p></td>
    </tr>
  <tr>
    <td colspan="2" style="padding:10px;">
<img alt="Multisafepay" src="http://proefdruk.factorygroep.nl/app/proefdruk/img/mail-logo2.jpg" />
</td>
    </tr>
</table>

</body>
</html>