<body style="background:#fff;font-family:arial;">
<table border="0" align="center" cellpadding="0" cellspacing="0" style="white-space: inherit;border:1px solid #ccc; padding:10px;width:696px;">
  <tr>
    <td colspan="2" style="padding:10px;">
<img alt="Multisafepay" src="http://proefdruk.factorygroep.nl/app/proefdruk/img/mail-logo2.jpg" />
</td>
  </tr>
  <tr>
    <td colspan="2"><div style="font:20px Arial, Helvetica, sans-serif; color:#000; padding:20px 0 20px 0px; float:left; width:100%">Beste <?php echo $this->name;?>,</div></td>
  </tr>
  <tr>
    <td colspan="2"><div style="font:bold 15px Arial, Helvetica, sans-serif; color:#000; padding:20px 0 20px 0px; float:left; width:100%;">Bedankt voor uw reactie op onze proefdruk: <?php echo $this->proof_number; ?> </td>
  </tr>

  <tr>
    <td colspan="2"><p style="font:13px Arial, Helvetica, sans-serif;">U heeft de betaling reeds via ons online betaalsysteem verricht. <br>
	We zullen de order nu voor u reserveren op voorraad. Daarna word uw order in productie geplaatst.</p></td>
  </tr>

<tr>
    <td colspan="2">
    	<p style="margin-top:50px; font:13px Arial, Helvetica, sans-serif;">
Hopende u hiermee voldoende te hebben geinformeerd.
		</br></br>
		Mocht u nog vragen hebben dan vernemen wij het graag.
		
		<br /><br/>
-Bel ons op NL: 085- 7325 999 of BE: 03 / 500 9417
<br />
-Mail ons: <a href="info@factorygroep.nl">info@factorygroep.nl</a> 
</p></td>
    </tr>
  <tr>
    <td colspan="2" style="padding:10px;">
<img alt="Multisafepay" src="http://proefdruk.factorygroep.nl/app/proefdruk/img/mail-logo2.jpg" />
</td>
    </tr>
</table>

</body>
</html>