<?php $proefdruk = $this->proefdruk;?>
<body style="background:#fff;font-family:arial;color: rgb(69, 65, 65);">
<table border="0" align="center" cellpadding="0" cellspacing="0" style="white-space: inherit;border:1px solid #ccc; padding:10px;width:710px;">
  <tr>
    <td colspan="2" style="padding:10px;">
<img alt="Multisafepay" src="http://proefdruk.factorygroep.nl/app/proefdruk/img/mail-logo2.jpg" />
</td>
  </tr>
  <tr>
    <td colspan="2"><div style="font:20px Arial, Helvetica, sans-serif; color:#000; padding:20px 0 20px 0px; float:left; width:100%">Beste <?php echo $proefdruk->proof_customer_name;?>,</div></td>
  </tr>
  <tr>
    <td colspan="2"><p style="font:12px Arial, Helvetica, sans-serif;line-height: 22px; color: rgb(69, 65, 65);">Bedankt voor uw aanvraag, hierbij ontvangt u uw digitale proefdruk. U kunt deze gebruiken om na te gaan of alles op de juiste manier over zal komen. Is alles naar wens? U kunt dit online aangeven, net als wanneer u nog wijzigingen wenst. U kunt uw proefdruknummer en de link hieronder gebruiken om uw digitale proefdruk te bekijken. </p></td>
  </tr>
  <tr>
    <td colspan="2"><div style="font:bold 15px Arial, Helvetica, sans-serif; color:#000; padding:20px 0 20px 0px; float:left; width:100%;">Uw proefdruknummer: <?php echo $proefdruk->proof_number;?></div></td>
  </tr>
 

  <tr>
    <td colspan="2" style="margin-top:30px;">
<a target="_blank" href="http://proefdruk.factorygroep.nl/app/proefdruk/proefdruk/index/<?php echo base64_encode($proefdruk->proof_id);?>" style="text-decoration:none;width:60%; display:block; margin:auto; border:1px solid #999; clear:both; margin:40px 0 0px 115px; padding:15px; text-align:center; color:#87b51e; font:bold 16px Arial, Helvetica, sans-serif;">Bekijk hier uw digitale proefdruk</a>
</td>
    </tr><tr></tr>
  <tr>
    <td colspan="2">
      <p style="font:12px Arial, Helvetica, sans-serif;line-height: 22px; color: rgb(69, 65, 65);">
Heeft u vragen over uw digitale proefdruk, of onze dienstverlening?<br> 
Neem vrijblijvend contact op via de onderstaande gegevens:

<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp; - Tel. Nr NL: 085 - 7325 999
<br />
&nbsp;&nbsp;&nbsp;&nbsp; - Tel. Nr BE: 03 / 500 9417
<br />
&nbsp;&nbsp;&nbsp;&nbsp; - E-mail: <a href="info@factorygroep.nl">info@factorygroep.nl</a> 
<br>
<br>
Met vriendelijke groet
</p></td>
    </tr>
  <tr>
    <td colspan="2" style="padding:10px;">
<img alt="Multisafepay" src="http://proefdruk.factorygroep.nl/app/proefdruk/img/mail-logo2.jpg" />
</td>
    </tr>
</table>

</body>
</html>