
	</div>
	
	<!-- JQueryUI v1.9.2 -->
	<script src="/app/proefdruk/theme/scripts/jquery-ui-1.9.2.custom/js/jquery-ui-1.9.2.custom.min.js"></script>
	
	<!-- JQueryUI Touch Punch -->
	<!-- small hack that enables the use of touch events on sites using the jQuery UI user interface library -->
	<script src="/app/proefdruk/theme/scripts/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
	
	<!-- MiniColors -->
	<script src="/app/proefdruk/theme/scripts/jquery-miniColors/jquery.miniColors.js"></script>
	
	<!-- Select2 -->
	<script src="/app/proefdruk/theme/scripts/select2/select2.js"></script>
	
	<!-- Themer -->
	<script>
	var themerPrimaryColor = '#DA4C4C';
	</script>
	<script src="/app/proefdruk/theme/scripts/jquery.cookie.js"></script>
	<script src="/app/proefdruk/theme/scripts/themer.js"></script>
	
	<!-- jQuery Validate -->
	<script src="/app/proefdruk/theme/scripts/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
	<script src="/app/proefdruk/theme/scripts/form_validator.js" type="text/javascript"></script>
<!-- DataTables -->
	<script src="/app/proefdruk/theme/scripts/DataTables/media/js/jquery.dataTables.min.js"></script>
	<script src="/app/proefdruk/theme/scripts/DataTables/media/js/DT_bootstrap.js"></script>
	
	<!-- Resize Script -->
	<script src="/app/proefdruk/theme/scripts/jquery.ba-resize.js"></script>
	
	<!-- Uniform -->
	<script src="/app/proefdruk/theme/scripts/pixelmatrix-uniform/jquery.uniform.min.js"></script>
	
	<!-- Bootstrap Script -->
	<script src="/app/proefdruk/bootstrap/js/bootstrap.min.js"></script>
	
	<!-- Bootstrap Extended -->
	<script src="/app/proefdruk/bootstrap/extend/bootstrap-select/bootstrap-select.js"></script>
	<script src="/app/proefdruk/bootstrap/extend/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js"></script>
	<script src="/app/proefdruk/bootstrap/extend/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js"></script>
	<script src="/app/proefdruk/bootstrap/extend/jasny-bootstrap/js/jasny-bootstrap.min.js" type="text/javascript"></script>
	<script src="/app/proefdruk/bootstrap/extend/jasny-bootstrap/js/bootstrap-fileupload.js" type="text/javascript"></script>
	<script src="/app/proefdruk/bootstrap/extend/bootbox.js" type="text/javascript"></script>
	<script src="/app/proefdruk/bootstrap/extend/bootstrap-wysihtml5/js/wysihtml5-0.3.0_rc2.min.js" type="text/javascript"></script>
	<script src="/app/proefdruk/bootstrap/extend/bootstrap-wysihtml5/js/bootstrap-wysihtml5-0.0.2.js" type="text/javascript"></script>
	
	<!-- Custom Onload Script -->
	<script src="/app/proefdruk/theme/scripts/load.js?1"></script>
	
	<!-- Layout Options -->
	<script src="/app/proefdruk/theme/scripts/layout.js"></script>
	
</body>
</html>